services:
  jaeger:
    image: harbor-gn2.cicd.s15m.nl/docker-hub/library/eclipse-temurin:17
    ports:
      - "8080:8080" # web
      - "9080:9080" # api
      #- "4317:4317"
    build:
      dockerfile: "../app-opera/src/docker/Dockerfile"
    environment:
      - LOG_LEVEL=debug
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
    name: my-network
